"""add profile table

Revision ID: 392aff377847
Revises: 43ad5c09c5b0
Create Date: 2026-05-14 18:34:17.012572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392aff377847'
down_revision = '43ad5c09c5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('favorite_cuisine', sa.String(length=80), nullable=True),
    sa.Column('years_cooking', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
